### ISSUE TITLE
这是你自己写的的吗？

### ISSUE THREAD

**Issue by martinwithyou** [forthealllight/blog#56]
一个实习生，怎么知道这么多？

**Comment by forthealllight** [comment]
> 一个实习生，怎么知道这么多？

自己写的，早就不是实习生了哦～～

**Comment by martinwithyou** [comment]
> > 一个实习生，怎么知道这么多？
> 
> 自己写的，早就不是实习生了哦～～

不好意思，
我看错了，
是一个实习生fork了你的项目。。。
