### ISSUE TITLE
转载申请

### ISSUE THREAD

**Issue by sisterAn** [forthealllight/blog#64]
已star、watch，向大佬学习，React hooks中swr的原理和源码解析与在Typescript项目中，如何优雅的使用ESLint和Prettier可以转载到公众号高级前端进阶上吗？会标明作者与来源，感谢

**Comment by forthealllight** [comment]
> 已star、watch，向大佬学习，React hooks中swr的原理和源码解析与在Typescript项目中，如何优雅的使用ESLint和Prettier可以转载到公众号高级前端进阶上吗？会标明作者与来源，感谢

可以
